// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6bfxXkNvpVq4Puu2KqYwA7p21vVidYg4',
    appId: '1:863831848874:web:95cf36931f152b1ad65dd3',
    messagingSenderId: '863831848874',
    projectId: 'maadih-c95a8',
    authDomain: 'maadih-c95a8.firebaseapp.com',
    storageBucket: 'maadih-c95a8.appspot.com',
    measurementId: 'G-YLEDM20F5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzZonpfW8Pev0oBnvbK6QIvGowJ45DiBo',
    appId: '1:863831848874:android:46eb93e826a16c3ed65dd3',
    messagingSenderId: '863831848874',
    projectId: 'maadih-c95a8',
    storageBucket: 'maadih-c95a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZW2wlXV3lMcBgjLnvY-Q2a1i-Xztd8Vg',
    appId: '1:863831848874:ios:a5830f36cec966e6d65dd3',
    messagingSenderId: '863831848874',
    projectId: 'maadih-c95a8',
    storageBucket: 'maadih-c95a8.appspot.com',
    iosBundleId: 'com.example.madh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZW2wlXV3lMcBgjLnvY-Q2a1i-Xztd8Vg',
    appId: '1:863831848874:ios:a5830f36cec966e6d65dd3',
    messagingSenderId: '863831848874',
    projectId: 'maadih-c95a8',
    storageBucket: 'maadih-c95a8.appspot.com',
    iosBundleId: 'com.example.madh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6bfxXkNvpVq4Puu2KqYwA7p21vVidYg4',
    appId: '1:863831848874:web:78b5684b7669e4ddd65dd3',
    messagingSenderId: '863831848874',
    projectId: 'maadih-c95a8',
    authDomain: 'maadih-c95a8.firebaseapp.com',
    storageBucket: 'maadih-c95a8.appspot.com',
    measurementId: 'G-E7G2CXC2B9',
  );
}
